// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: binvalue.proto

package com.kayzen.impcount.aerospike.api;

public final class Binvalue {
  private Binvalue() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BinDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kayzen.impcount.aerospike.api.BinData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string value = 1 [default = ""];</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>optional string value = 1 [default = ""];</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>optional string value = 1 [default = ""];</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>optional .com.kayzen.impcount.aerospike.api.FcapData fcapValue = 2;</code>
     * @return Whether the fcapValue field is set.
     */
    boolean hasFcapValue();
    /**
     * <code>optional .com.kayzen.impcount.aerospike.api.FcapData fcapValue = 2;</code>
     * @return The fcapValue.
     */
    com.kayzen.impcount.aerospike.api.Fcapdata.FcapData getFcapValue();
    /**
     * <code>optional .com.kayzen.impcount.aerospike.api.FcapData fcapValue = 2;</code>
     */
    com.kayzen.impcount.aerospike.api.Fcapdata.FcapDataOrBuilder getFcapValueOrBuilder();
  }
  /**
   * Protobuf type {@code com.kayzen.impcount.aerospike.api.BinData}
   */
  public  static final class BinData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.kayzen.impcount.aerospike.api.BinData)
      BinDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BinData.newBuilder() to construct.
    private BinData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BinData() {
      value_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BinData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BinData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              value_ = bs;
              break;
            }
            case 18: {
              com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = fcapValue_.toBuilder();
              }
              fcapValue_ = input.readMessage(com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fcapValue_);
                fcapValue_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kayzen.impcount.aerospike.api.Binvalue.internal_static_com_kayzen_impcount_aerospike_api_BinData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kayzen.impcount.aerospike.api.Binvalue.internal_static_com_kayzen_impcount_aerospike_api_BinData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kayzen.impcount.aerospike.api.Binvalue.BinData.class, com.kayzen.impcount.aerospike.api.Binvalue.BinData.Builder.class);
    }

    private int bitField0_;
    public static final int VALUE_FIELD_NUMBER = 1;
    private volatile java.lang.Object value_;
    /**
     * <code>optional string value = 1 [default = ""];</code>
     * @return Whether the value field is set.
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string value = 1 [default = ""];</code>
     * @return The value.
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string value = 1 [default = ""];</code>
     * @return The bytes for value.
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FCAPVALUE_FIELD_NUMBER = 2;
    private com.kayzen.impcount.aerospike.api.Fcapdata.FcapData fcapValue_;
    /**
     * <code>optional .com.kayzen.impcount.aerospike.api.FcapData fcapValue = 2;</code>
     * @return Whether the fcapValue field is set.
     */
    public boolean hasFcapValue() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .com.kayzen.impcount.aerospike.api.FcapData fcapValue = 2;</code>
     * @return The fcapValue.
     */
    public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData getFcapValue() {
      return fcapValue_ == null ? com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.getDefaultInstance() : fcapValue_;
    }
    /**
     * <code>optional .com.kayzen.impcount.aerospike.api.FcapData fcapValue = 2;</code>
     */
    public com.kayzen.impcount.aerospike.api.Fcapdata.FcapDataOrBuilder getFcapValueOrBuilder() {
      return fcapValue_ == null ? com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.getDefaultInstance() : fcapValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getFcapValue());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFcapValue());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kayzen.impcount.aerospike.api.Binvalue.BinData)) {
        return super.equals(obj);
      }
      com.kayzen.impcount.aerospike.api.Binvalue.BinData other = (com.kayzen.impcount.aerospike.api.Binvalue.BinData) obj;

      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (hasFcapValue() != other.hasFcapValue()) return false;
      if (hasFcapValue()) {
        if (!getFcapValue()
            .equals(other.getFcapValue())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      if (hasFcapValue()) {
        hash = (37 * hash) + FCAPVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getFcapValue().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kayzen.impcount.aerospike.api.Binvalue.BinData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kayzen.impcount.aerospike.api.Binvalue.BinData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kayzen.impcount.aerospike.api.Binvalue.BinData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kayzen.impcount.aerospike.api.Binvalue.BinData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kayzen.impcount.aerospike.api.Binvalue.BinData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kayzen.impcount.aerospike.api.Binvalue.BinData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kayzen.impcount.aerospike.api.Binvalue.BinData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kayzen.impcount.aerospike.api.Binvalue.BinData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kayzen.impcount.aerospike.api.Binvalue.BinData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kayzen.impcount.aerospike.api.Binvalue.BinData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kayzen.impcount.aerospike.api.Binvalue.BinData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kayzen.impcount.aerospike.api.Binvalue.BinData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kayzen.impcount.aerospike.api.Binvalue.BinData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kayzen.impcount.aerospike.api.BinData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kayzen.impcount.aerospike.api.BinData)
        com.kayzen.impcount.aerospike.api.Binvalue.BinDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kayzen.impcount.aerospike.api.Binvalue.internal_static_com_kayzen_impcount_aerospike_api_BinData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kayzen.impcount.aerospike.api.Binvalue.internal_static_com_kayzen_impcount_aerospike_api_BinData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kayzen.impcount.aerospike.api.Binvalue.BinData.class, com.kayzen.impcount.aerospike.api.Binvalue.BinData.Builder.class);
      }

      // Construct using com.kayzen.impcount.aerospike.api.Binvalue.BinData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFcapValueFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (fcapValueBuilder_ == null) {
          fcapValue_ = null;
        } else {
          fcapValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kayzen.impcount.aerospike.api.Binvalue.internal_static_com_kayzen_impcount_aerospike_api_BinData_descriptor;
      }

      @java.lang.Override
      public com.kayzen.impcount.aerospike.api.Binvalue.BinData getDefaultInstanceForType() {
        return com.kayzen.impcount.aerospike.api.Binvalue.BinData.getDefaultInstance();
      }

      @java.lang.Override
      public com.kayzen.impcount.aerospike.api.Binvalue.BinData build() {
        com.kayzen.impcount.aerospike.api.Binvalue.BinData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kayzen.impcount.aerospike.api.Binvalue.BinData buildPartial() {
        com.kayzen.impcount.aerospike.api.Binvalue.BinData result = new com.kayzen.impcount.aerospike.api.Binvalue.BinData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (fcapValueBuilder_ == null) {
            result.fcapValue_ = fcapValue_;
          } else {
            result.fcapValue_ = fcapValueBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kayzen.impcount.aerospike.api.Binvalue.BinData) {
          return mergeFrom((com.kayzen.impcount.aerospike.api.Binvalue.BinData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kayzen.impcount.aerospike.api.Binvalue.BinData other) {
        if (other == com.kayzen.impcount.aerospike.api.Binvalue.BinData.getDefaultInstance()) return this;
        if (other.hasValue()) {
          bitField0_ |= 0x00000001;
          value_ = other.value_;
          onChanged();
        }
        if (other.hasFcapValue()) {
          mergeFcapValue(other.getFcapValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kayzen.impcount.aerospike.api.Binvalue.BinData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kayzen.impcount.aerospike.api.Binvalue.BinData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object value_ = "";
      /**
       * <code>optional string value = 1 [default = ""];</code>
       * @return Whether the value field is set.
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string value = 1 [default = ""];</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value = 1 [default = ""];</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value = 1 [default = ""];</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 1 [default = ""];</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 1 [default = ""];</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }

      private com.kayzen.impcount.aerospike.api.Fcapdata.FcapData fcapValue_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kayzen.impcount.aerospike.api.Fcapdata.FcapData, com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.Builder, com.kayzen.impcount.aerospike.api.Fcapdata.FcapDataOrBuilder> fcapValueBuilder_;
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData fcapValue = 2;</code>
       * @return Whether the fcapValue field is set.
       */
      public boolean hasFcapValue() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData fcapValue = 2;</code>
       * @return The fcapValue.
       */
      public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData getFcapValue() {
        if (fcapValueBuilder_ == null) {
          return fcapValue_ == null ? com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.getDefaultInstance() : fcapValue_;
        } else {
          return fcapValueBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData fcapValue = 2;</code>
       */
      public Builder setFcapValue(com.kayzen.impcount.aerospike.api.Fcapdata.FcapData value) {
        if (fcapValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fcapValue_ = value;
          onChanged();
        } else {
          fcapValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData fcapValue = 2;</code>
       */
      public Builder setFcapValue(
          com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.Builder builderForValue) {
        if (fcapValueBuilder_ == null) {
          fcapValue_ = builderForValue.build();
          onChanged();
        } else {
          fcapValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData fcapValue = 2;</code>
       */
      public Builder mergeFcapValue(com.kayzen.impcount.aerospike.api.Fcapdata.FcapData value) {
        if (fcapValueBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              fcapValue_ != null &&
              fcapValue_ != com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.getDefaultInstance()) {
            fcapValue_ =
              com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.newBuilder(fcapValue_).mergeFrom(value).buildPartial();
          } else {
            fcapValue_ = value;
          }
          onChanged();
        } else {
          fcapValueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData fcapValue = 2;</code>
       */
      public Builder clearFcapValue() {
        if (fcapValueBuilder_ == null) {
          fcapValue_ = null;
          onChanged();
        } else {
          fcapValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData fcapValue = 2;</code>
       */
      public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.Builder getFcapValueBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getFcapValueFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData fcapValue = 2;</code>
       */
      public com.kayzen.impcount.aerospike.api.Fcapdata.FcapDataOrBuilder getFcapValueOrBuilder() {
        if (fcapValueBuilder_ != null) {
          return fcapValueBuilder_.getMessageOrBuilder();
        } else {
          return fcapValue_ == null ?
              com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.getDefaultInstance() : fcapValue_;
        }
      }
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData fcapValue = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kayzen.impcount.aerospike.api.Fcapdata.FcapData, com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.Builder, com.kayzen.impcount.aerospike.api.Fcapdata.FcapDataOrBuilder> 
          getFcapValueFieldBuilder() {
        if (fcapValueBuilder_ == null) {
          fcapValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.kayzen.impcount.aerospike.api.Fcapdata.FcapData, com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.Builder, com.kayzen.impcount.aerospike.api.Fcapdata.FcapDataOrBuilder>(
                  getFcapValue(),
                  getParentForChildren(),
                  isClean());
          fcapValue_ = null;
        }
        return fcapValueBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.kayzen.impcount.aerospike.api.BinData)
    }

    // @@protoc_insertion_point(class_scope:com.kayzen.impcount.aerospike.api.BinData)
    private static final com.kayzen.impcount.aerospike.api.Binvalue.BinData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kayzen.impcount.aerospike.api.Binvalue.BinData();
    }

    public static com.kayzen.impcount.aerospike.api.Binvalue.BinData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BinData>
        PARSER = new com.google.protobuf.AbstractParser<BinData>() {
      @java.lang.Override
      public BinData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BinData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BinData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BinData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kayzen.impcount.aerospike.api.Binvalue.BinData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kayzen_impcount_aerospike_api_BinData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kayzen_impcount_aerospike_api_BinData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016binvalue.proto\022!com.kayzen.impcount.ae" +
      "rospike.api\032\016fcapdata.proto\"Z\n\007BinData\022\017" +
      "\n\005value\030\001 \001(\t:\000\022>\n\tfcapValue\030\002 \001(\0132+.com" +
      ".kayzen.impcount.aerospike.api.FcapData"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kayzen.impcount.aerospike.api.Fcapdata.getDescriptor(),
        });
    internal_static_com_kayzen_impcount_aerospike_api_BinData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kayzen_impcount_aerospike_api_BinData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kayzen_impcount_aerospike_api_BinData_descriptor,
        new java.lang.String[] { "Value", "FcapValue", });
    com.kayzen.impcount.aerospike.api.Fcapdata.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
