// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fcapdata.proto

package com.kayzen.impcount.aerospike.api;

public final class Fcapdata {
  private Fcapdata() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FcapDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kayzen.impcount.aerospike.api.FcapData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
     */
    java.util.List<com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem> 
        getValueList();
    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
     */
    com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem getValue(int index);
    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
     */
    int getValueCount();
    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
     */
    java.util.List<? extends com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItemOrBuilder> 
        getValueOrBuilderList();
    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
     */
    com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItemOrBuilder getValueOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.kayzen.impcount.aerospike.api.FcapData}
   */
  public  static final class FcapData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.kayzen.impcount.aerospike.api.FcapData)
      FcapDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FcapData.newBuilder() to construct.
    private FcapData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FcapData() {
      value_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FcapData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FcapData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                value_ = new java.util.ArrayList<com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              value_.add(
                  input.readMessage(com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          value_ = java.util.Collections.unmodifiableList(value_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kayzen.impcount.aerospike.api.Fcapdata.internal_static_com_kayzen_impcount_aerospike_api_FcapData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kayzen.impcount.aerospike.api.Fcapdata.internal_static_com_kayzen_impcount_aerospike_api_FcapData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.class, com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.Builder.class);
    }

    /**
     * Protobuf enum {@code com.kayzen.impcount.aerospike.api.FcapData.option}
     */
    public enum option
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>add = 0;</code>
       */
      add(0),
      /**
       * <code>remove = 1;</code>
       */
      remove(1),
      ;

      /**
       * <code>add = 0;</code>
       */
      public static final int add_VALUE = 0;
      /**
       * <code>remove = 1;</code>
       */
      public static final int remove_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static option valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static option forNumber(int value) {
        switch (value) {
          case 0: return add;
          case 1: return remove;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<option>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          option> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<option>() {
              public option findValueByNumber(int number) {
                return option.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.getDescriptor().getEnumTypes().get(0);
      }

      private static final option[] VALUES = values();

      public static option valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private option(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.kayzen.impcount.aerospike.api.FcapData.option)
    }

    /**
     * Protobuf enum {@code com.kayzen.impcount.aerospike.api.FcapData.capType}
     */
    public enum capType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>impression = 0;</code>
       */
      impression(0),
      /**
       * <code>click = 1;</code>
       */
      click(1),
      /**
       * <code>install = 2;</code>
       */
      install(2),
      ;

      /**
       * <code>impression = 0;</code>
       */
      public static final int impression_VALUE = 0;
      /**
       * <code>click = 1;</code>
       */
      public static final int click_VALUE = 1;
      /**
       * <code>install = 2;</code>
       */
      public static final int install_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static capType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static capType forNumber(int value) {
        switch (value) {
          case 0: return impression;
          case 1: return click;
          case 2: return install;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<capType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          capType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<capType>() {
              public capType findValueByNumber(int number) {
                return capType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.getDescriptor().getEnumTypes().get(1);
      }

      private static final capType[] VALUES = values();

      public static capType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private capType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.kayzen.impcount.aerospike.api.FcapData.capType)
    }

    /**
     * Protobuf enum {@code com.kayzen.impcount.aerospike.api.FcapData.campaignOrLineItem}
     */
    public enum campaignOrLineItem
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>campaign = 0;</code>
       */
      campaign(0),
      /**
       * <code>lineitem = 1;</code>
       */
      lineitem(1),
      ;

      /**
       * <code>campaign = 0;</code>
       */
      public static final int campaign_VALUE = 0;
      /**
       * <code>lineitem = 1;</code>
       */
      public static final int lineitem_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static campaignOrLineItem valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static campaignOrLineItem forNumber(int value) {
        switch (value) {
          case 0: return campaign;
          case 1: return lineitem;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<campaignOrLineItem>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          campaignOrLineItem> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<campaignOrLineItem>() {
              public campaignOrLineItem findValueByNumber(int number) {
                return campaignOrLineItem.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.getDescriptor().getEnumTypes().get(2);
      }

      private static final campaignOrLineItem[] VALUES = values();

      public static campaignOrLineItem valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private campaignOrLineItem(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.kayzen.impcount.aerospike.api.FcapData.campaignOrLineItem)
    }

    public interface fcapCampaignOrLineItemOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 campaignOrLineItemID = 1;</code>
       * @return Whether the campaignOrLineItemID field is set.
       */
      boolean hasCampaignOrLineItemID();
      /**
       * <code>optional int32 campaignOrLineItemID = 1;</code>
       * @return The campaignOrLineItemID.
       */
      int getCampaignOrLineItemID();

      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.option option = 2;</code>
       * @return Whether the option field is set.
       */
      boolean hasOption();
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.option option = 2;</code>
       * @return The option.
       */
      com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.option getOption();

      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.capType capType = 3;</code>
       * @return Whether the capType field is set.
       */
      boolean hasCapType();
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.capType capType = 3;</code>
       * @return The capType.
       */
      com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.capType getCapType();

      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.campaignOrLineItem campaignOrLineItem = 4;</code>
       * @return Whether the campaignOrLineItem field is set.
       */
      boolean hasCampaignOrLineItem();
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.campaignOrLineItem campaignOrLineItem = 4;</code>
       * @return The campaignOrLineItem.
       */
      com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.campaignOrLineItem getCampaignOrLineItem();
    }
    /**
     * Protobuf type {@code com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem}
     */
    public  static final class fcapCampaignOrLineItem extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem)
        fcapCampaignOrLineItemOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use fcapCampaignOrLineItem.newBuilder() to construct.
      private fcapCampaignOrLineItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private fcapCampaignOrLineItem() {
        option_ = 0;
        capType_ = 0;
        campaignOrLineItem_ = 0;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new fcapCampaignOrLineItem();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private fcapCampaignOrLineItem(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                bitField0_ |= 0x00000001;
                campaignOrLineItemID_ = input.readInt32();
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                  @SuppressWarnings("deprecation")
                com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.option value = com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.option.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  option_ = rawValue;
                }
                break;
              }
              case 24: {
                int rawValue = input.readEnum();
                  @SuppressWarnings("deprecation")
                com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.capType value = com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.capType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(3, rawValue);
                } else {
                  bitField0_ |= 0x00000004;
                  capType_ = rawValue;
                }
                break;
              }
              case 32: {
                int rawValue = input.readEnum();
                  @SuppressWarnings("deprecation")
                com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.campaignOrLineItem value = com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.campaignOrLineItem.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(4, rawValue);
                } else {
                  bitField0_ |= 0x00000008;
                  campaignOrLineItem_ = rawValue;
                }
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kayzen.impcount.aerospike.api.Fcapdata.internal_static_com_kayzen_impcount_aerospike_api_FcapData_fcapCampaignOrLineItem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kayzen.impcount.aerospike.api.Fcapdata.internal_static_com_kayzen_impcount_aerospike_api_FcapData_fcapCampaignOrLineItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.class, com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.Builder.class);
      }

      private int bitField0_;
      public static final int CAMPAIGNORLINEITEMID_FIELD_NUMBER = 1;
      private int campaignOrLineItemID_;
      /**
       * <code>optional int32 campaignOrLineItemID = 1;</code>
       * @return Whether the campaignOrLineItemID field is set.
       */
      public boolean hasCampaignOrLineItemID() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 campaignOrLineItemID = 1;</code>
       * @return The campaignOrLineItemID.
       */
      public int getCampaignOrLineItemID() {
        return campaignOrLineItemID_;
      }

      public static final int OPTION_FIELD_NUMBER = 2;
      private int option_;
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.option option = 2;</code>
       * @return Whether the option field is set.
       */
      public boolean hasOption() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.option option = 2;</code>
       * @return The option.
       */
      public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.option getOption() {
        @SuppressWarnings("deprecation")
        com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.option result = com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.option.valueOf(option_);
        return result == null ? com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.option.add : result;
      }

      public static final int CAPTYPE_FIELD_NUMBER = 3;
      private int capType_;
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.capType capType = 3;</code>
       * @return Whether the capType field is set.
       */
      public boolean hasCapType() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.capType capType = 3;</code>
       * @return The capType.
       */
      public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.capType getCapType() {
        @SuppressWarnings("deprecation")
        com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.capType result = com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.capType.valueOf(capType_);
        return result == null ? com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.capType.impression : result;
      }

      public static final int CAMPAIGNORLINEITEM_FIELD_NUMBER = 4;
      private int campaignOrLineItem_;
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.campaignOrLineItem campaignOrLineItem = 4;</code>
       * @return Whether the campaignOrLineItem field is set.
       */
      public boolean hasCampaignOrLineItem() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.campaignOrLineItem campaignOrLineItem = 4;</code>
       * @return The campaignOrLineItem.
       */
      public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.campaignOrLineItem getCampaignOrLineItem() {
        @SuppressWarnings("deprecation")
        com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.campaignOrLineItem result = com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.campaignOrLineItem.valueOf(campaignOrLineItem_);
        return result == null ? com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.campaignOrLineItem.campaign : result;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeInt32(1, campaignOrLineItemID_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeEnum(2, option_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          output.writeEnum(3, capType_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          output.writeEnum(4, campaignOrLineItem_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, campaignOrLineItemID_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, option_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(3, capType_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(4, campaignOrLineItem_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem)) {
          return super.equals(obj);
        }
        com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem other = (com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem) obj;

        if (hasCampaignOrLineItemID() != other.hasCampaignOrLineItemID()) return false;
        if (hasCampaignOrLineItemID()) {
          if (getCampaignOrLineItemID()
              != other.getCampaignOrLineItemID()) return false;
        }
        if (hasOption() != other.hasOption()) return false;
        if (hasOption()) {
          if (option_ != other.option_) return false;
        }
        if (hasCapType() != other.hasCapType()) return false;
        if (hasCapType()) {
          if (capType_ != other.capType_) return false;
        }
        if (hasCampaignOrLineItem() != other.hasCampaignOrLineItem()) return false;
        if (hasCampaignOrLineItem()) {
          if (campaignOrLineItem_ != other.campaignOrLineItem_) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasCampaignOrLineItemID()) {
          hash = (37 * hash) + CAMPAIGNORLINEITEMID_FIELD_NUMBER;
          hash = (53 * hash) + getCampaignOrLineItemID();
        }
        if (hasOption()) {
          hash = (37 * hash) + OPTION_FIELD_NUMBER;
          hash = (53 * hash) + option_;
        }
        if (hasCapType()) {
          hash = (37 * hash) + CAPTYPE_FIELD_NUMBER;
          hash = (53 * hash) + capType_;
        }
        if (hasCampaignOrLineItem()) {
          hash = (37 * hash) + CAMPAIGNORLINEITEM_FIELD_NUMBER;
          hash = (53 * hash) + campaignOrLineItem_;
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem)
          com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.kayzen.impcount.aerospike.api.Fcapdata.internal_static_com_kayzen_impcount_aerospike_api_FcapData_fcapCampaignOrLineItem_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.kayzen.impcount.aerospike.api.Fcapdata.internal_static_com_kayzen_impcount_aerospike_api_FcapData_fcapCampaignOrLineItem_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.class, com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.Builder.class);
        }

        // Construct using com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          campaignOrLineItemID_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          option_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          capType_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          campaignOrLineItem_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.kayzen.impcount.aerospike.api.Fcapdata.internal_static_com_kayzen_impcount_aerospike_api_FcapData_fcapCampaignOrLineItem_descriptor;
        }

        @java.lang.Override
        public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem getDefaultInstanceForType() {
          return com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.getDefaultInstance();
        }

        @java.lang.Override
        public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem build() {
          com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem buildPartial() {
          com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem result = new com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.campaignOrLineItemID_ = campaignOrLineItemID_;
            to_bitField0_ |= 0x00000001;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            to_bitField0_ |= 0x00000002;
          }
          result.option_ = option_;
          if (((from_bitField0_ & 0x00000004) != 0)) {
            to_bitField0_ |= 0x00000004;
          }
          result.capType_ = capType_;
          if (((from_bitField0_ & 0x00000008) != 0)) {
            to_bitField0_ |= 0x00000008;
          }
          result.campaignOrLineItem_ = campaignOrLineItem_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem) {
            return mergeFrom((com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem other) {
          if (other == com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.getDefaultInstance()) return this;
          if (other.hasCampaignOrLineItemID()) {
            setCampaignOrLineItemID(other.getCampaignOrLineItemID());
          }
          if (other.hasOption()) {
            setOption(other.getOption());
          }
          if (other.hasCapType()) {
            setCapType(other.getCapType());
          }
          if (other.hasCampaignOrLineItem()) {
            setCampaignOrLineItem(other.getCampaignOrLineItem());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int campaignOrLineItemID_ ;
        /**
         * <code>optional int32 campaignOrLineItemID = 1;</code>
         * @return Whether the campaignOrLineItemID field is set.
         */
        public boolean hasCampaignOrLineItemID() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional int32 campaignOrLineItemID = 1;</code>
         * @return The campaignOrLineItemID.
         */
        public int getCampaignOrLineItemID() {
          return campaignOrLineItemID_;
        }
        /**
         * <code>optional int32 campaignOrLineItemID = 1;</code>
         * @param value The campaignOrLineItemID to set.
         * @return This builder for chaining.
         */
        public Builder setCampaignOrLineItemID(int value) {
          bitField0_ |= 0x00000001;
          campaignOrLineItemID_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 campaignOrLineItemID = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearCampaignOrLineItemID() {
          bitField0_ = (bitField0_ & ~0x00000001);
          campaignOrLineItemID_ = 0;
          onChanged();
          return this;
        }

        private int option_ = 0;
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.option option = 2;</code>
         * @return Whether the option field is set.
         */
        public boolean hasOption() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.option option = 2;</code>
         * @return The option.
         */
        public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.option getOption() {
          @SuppressWarnings("deprecation")
          com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.option result = com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.option.valueOf(option_);
          return result == null ? com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.option.add : result;
        }
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.option option = 2;</code>
         * @param value The option to set.
         * @return This builder for chaining.
         */
        public Builder setOption(com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.option value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          option_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.option option = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearOption() {
          bitField0_ = (bitField0_ & ~0x00000002);
          option_ = 0;
          onChanged();
          return this;
        }

        private int capType_ = 0;
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.capType capType = 3;</code>
         * @return Whether the capType field is set.
         */
        public boolean hasCapType() {
          return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.capType capType = 3;</code>
         * @return The capType.
         */
        public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.capType getCapType() {
          @SuppressWarnings("deprecation")
          com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.capType result = com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.capType.valueOf(capType_);
          return result == null ? com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.capType.impression : result;
        }
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.capType capType = 3;</code>
         * @param value The capType to set.
         * @return This builder for chaining.
         */
        public Builder setCapType(com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.capType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000004;
          capType_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.capType capType = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearCapType() {
          bitField0_ = (bitField0_ & ~0x00000004);
          capType_ = 0;
          onChanged();
          return this;
        }

        private int campaignOrLineItem_ = 0;
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.campaignOrLineItem campaignOrLineItem = 4;</code>
         * @return Whether the campaignOrLineItem field is set.
         */
        public boolean hasCampaignOrLineItem() {
          return ((bitField0_ & 0x00000008) != 0);
        }
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.campaignOrLineItem campaignOrLineItem = 4;</code>
         * @return The campaignOrLineItem.
         */
        public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.campaignOrLineItem getCampaignOrLineItem() {
          @SuppressWarnings("deprecation")
          com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.campaignOrLineItem result = com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.campaignOrLineItem.valueOf(campaignOrLineItem_);
          return result == null ? com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.campaignOrLineItem.campaign : result;
        }
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.campaignOrLineItem campaignOrLineItem = 4;</code>
         * @param value The campaignOrLineItem to set.
         * @return This builder for chaining.
         */
        public Builder setCampaignOrLineItem(com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.campaignOrLineItem value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000008;
          campaignOrLineItem_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.FcapData.campaignOrLineItem campaignOrLineItem = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearCampaignOrLineItem() {
          bitField0_ = (bitField0_ & ~0x00000008);
          campaignOrLineItem_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem)
      }

      // @@protoc_insertion_point(class_scope:com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem)
      private static final com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem();
      }

      public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<fcapCampaignOrLineItem>
          PARSER = new com.google.protobuf.AbstractParser<fcapCampaignOrLineItem>() {
        @java.lang.Override
        public fcapCampaignOrLineItem parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new fcapCampaignOrLineItem(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<fcapCampaignOrLineItem> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<fcapCampaignOrLineItem> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private java.util.List<com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem> value_;
    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
     */
    public java.util.List<com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem> getValueList() {
      return value_;
    }
    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
     */
    public java.util.List<? extends com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItemOrBuilder> 
        getValueOrBuilderList() {
      return value_;
    }
    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
     */
    public int getValueCount() {
      return value_.size();
    }
    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
     */
    public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem getValue(int index) {
      return value_.get(index);
    }
    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
     */
    public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItemOrBuilder getValueOrBuilder(
        int index) {
      return value_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < value_.size(); i++) {
        output.writeMessage(1, value_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < value_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, value_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kayzen.impcount.aerospike.api.Fcapdata.FcapData)) {
        return super.equals(obj);
      }
      com.kayzen.impcount.aerospike.api.Fcapdata.FcapData other = (com.kayzen.impcount.aerospike.api.Fcapdata.FcapData) obj;

      if (!getValueList()
          .equals(other.getValueList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getValueCount() > 0) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValueList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kayzen.impcount.aerospike.api.Fcapdata.FcapData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kayzen.impcount.aerospike.api.FcapData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kayzen.impcount.aerospike.api.FcapData)
        com.kayzen.impcount.aerospike.api.Fcapdata.FcapDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kayzen.impcount.aerospike.api.Fcapdata.internal_static_com_kayzen_impcount_aerospike_api_FcapData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kayzen.impcount.aerospike.api.Fcapdata.internal_static_com_kayzen_impcount_aerospike_api_FcapData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.class, com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.Builder.class);
      }

      // Construct using com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getValueFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (valueBuilder_ == null) {
          value_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          valueBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kayzen.impcount.aerospike.api.Fcapdata.internal_static_com_kayzen_impcount_aerospike_api_FcapData_descriptor;
      }

      @java.lang.Override
      public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData getDefaultInstanceForType() {
        return com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.getDefaultInstance();
      }

      @java.lang.Override
      public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData build() {
        com.kayzen.impcount.aerospike.api.Fcapdata.FcapData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData buildPartial() {
        com.kayzen.impcount.aerospike.api.Fcapdata.FcapData result = new com.kayzen.impcount.aerospike.api.Fcapdata.FcapData(this);
        int from_bitField0_ = bitField0_;
        if (valueBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            value_ = java.util.Collections.unmodifiableList(value_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.value_ = value_;
        } else {
          result.value_ = valueBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kayzen.impcount.aerospike.api.Fcapdata.FcapData) {
          return mergeFrom((com.kayzen.impcount.aerospike.api.Fcapdata.FcapData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kayzen.impcount.aerospike.api.Fcapdata.FcapData other) {
        if (other == com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.getDefaultInstance()) return this;
        if (valueBuilder_ == null) {
          if (!other.value_.isEmpty()) {
            if (value_.isEmpty()) {
              value_ = other.value_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureValueIsMutable();
              value_.addAll(other.value_);
            }
            onChanged();
          }
        } else {
          if (!other.value_.isEmpty()) {
            if (valueBuilder_.isEmpty()) {
              valueBuilder_.dispose();
              valueBuilder_ = null;
              value_ = other.value_;
              bitField0_ = (bitField0_ & ~0x00000001);
              valueBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getValueFieldBuilder() : null;
            } else {
              valueBuilder_.addAllMessages(other.value_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kayzen.impcount.aerospike.api.Fcapdata.FcapData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kayzen.impcount.aerospike.api.Fcapdata.FcapData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem> value_ =
        java.util.Collections.emptyList();
      private void ensureValueIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          value_ = new java.util.ArrayList<com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem>(value_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem, com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.Builder, com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItemOrBuilder> valueBuilder_;

      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
       */
      public java.util.List<com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem> getValueList() {
        if (valueBuilder_ == null) {
          return java.util.Collections.unmodifiableList(value_);
        } else {
          return valueBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
       */
      public int getValueCount() {
        if (valueBuilder_ == null) {
          return value_.size();
        } else {
          return valueBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
       */
      public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem getValue(int index) {
        if (valueBuilder_ == null) {
          return value_.get(index);
        } else {
          return valueBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
       */
      public Builder setValue(
          int index, com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem value) {
        if (valueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValueIsMutable();
          value_.set(index, value);
          onChanged();
        } else {
          valueBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
       */
      public Builder setValue(
          int index, com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.Builder builderForValue) {
        if (valueBuilder_ == null) {
          ensureValueIsMutable();
          value_.set(index, builderForValue.build());
          onChanged();
        } else {
          valueBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
       */
      public Builder addValue(com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem value) {
        if (valueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValueIsMutable();
          value_.add(value);
          onChanged();
        } else {
          valueBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
       */
      public Builder addValue(
          int index, com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem value) {
        if (valueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValueIsMutable();
          value_.add(index, value);
          onChanged();
        } else {
          valueBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
       */
      public Builder addValue(
          com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.Builder builderForValue) {
        if (valueBuilder_ == null) {
          ensureValueIsMutable();
          value_.add(builderForValue.build());
          onChanged();
        } else {
          valueBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
       */
      public Builder addValue(
          int index, com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.Builder builderForValue) {
        if (valueBuilder_ == null) {
          ensureValueIsMutable();
          value_.add(index, builderForValue.build());
          onChanged();
        } else {
          valueBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
       */
      public Builder addAllValue(
          java.lang.Iterable<? extends com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem> values) {
        if (valueBuilder_ == null) {
          ensureValueIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, value_);
          onChanged();
        } else {
          valueBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
       */
      public Builder clearValue() {
        if (valueBuilder_ == null) {
          value_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          valueBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
       */
      public Builder removeValue(int index) {
        if (valueBuilder_ == null) {
          ensureValueIsMutable();
          value_.remove(index);
          onChanged();
        } else {
          valueBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
       */
      public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.Builder getValueBuilder(
          int index) {
        return getValueFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
       */
      public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItemOrBuilder getValueOrBuilder(
          int index) {
        if (valueBuilder_ == null) {
          return value_.get(index);  } else {
          return valueBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
       */
      public java.util.List<? extends com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItemOrBuilder> 
           getValueOrBuilderList() {
        if (valueBuilder_ != null) {
          return valueBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(value_);
        }
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
       */
      public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.Builder addValueBuilder() {
        return getValueFieldBuilder().addBuilder(
            com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
       */
      public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.Builder addValueBuilder(
          int index) {
        return getValueFieldBuilder().addBuilder(
            index, com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.FcapData.fcapCampaignOrLineItem value = 1;</code>
       */
      public java.util.List<com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.Builder> 
           getValueBuilderList() {
        return getValueFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem, com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.Builder, com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItemOrBuilder> 
          getValueFieldBuilder() {
        if (valueBuilder_ == null) {
          valueBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem, com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItem.Builder, com.kayzen.impcount.aerospike.api.Fcapdata.FcapData.fcapCampaignOrLineItemOrBuilder>(
                  value_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        return valueBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.kayzen.impcount.aerospike.api.FcapData)
    }

    // @@protoc_insertion_point(class_scope:com.kayzen.impcount.aerospike.api.FcapData)
    private static final com.kayzen.impcount.aerospike.api.Fcapdata.FcapData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kayzen.impcount.aerospike.api.Fcapdata.FcapData();
    }

    public static com.kayzen.impcount.aerospike.api.Fcapdata.FcapData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<FcapData>
        PARSER = new com.google.protobuf.AbstractParser<FcapData>() {
      @java.lang.Override
      public FcapData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FcapData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FcapData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FcapData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kayzen.impcount.aerospike.api.Fcapdata.FcapData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kayzen_impcount_aerospike_api_FcapData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kayzen_impcount_aerospike_api_FcapData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kayzen_impcount_aerospike_api_FcapData_fcapCampaignOrLineItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kayzen_impcount_aerospike_api_FcapData_fcapCampaignOrLineItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016fcapdata.proto\022!com.kayzen.impcount.ae" +
      "rospike.api\"\200\004\n\010FcapData\022Q\n\005value\030\001 \003(\0132" +
      "B.com.kayzen.impcount.aerospike.api.Fcap" +
      "Data.fcapCampaignOrLineItem\032\234\002\n\026fcapCamp" +
      "aignOrLineItem\022\034\n\024campaignOrLineItemID\030\001" +
      " \001(\005\022B\n\006option\030\002 \001(\01622.com.kayzen.impcou" +
      "nt.aerospike.api.FcapData.option\022D\n\007capT" +
      "ype\030\003 \001(\01623.com.kayzen.impcount.aerospik" +
      "e.api.FcapData.capType\022Z\n\022campaignOrLine" +
      "Item\030\004 \001(\0162>.com.kayzen.impcount.aerospi" +
      "ke.api.FcapData.campaignOrLineItem\"\035\n\006op" +
      "tion\022\007\n\003add\020\000\022\n\n\006remove\020\001\"1\n\007capType\022\016\n\n" +
      "impression\020\000\022\t\n\005click\020\001\022\013\n\007install\020\002\"0\n\022" +
      "campaignOrLineItem\022\014\n\010campaign\020\000\022\014\n\010line" +
      "item\020\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_kayzen_impcount_aerospike_api_FcapData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kayzen_impcount_aerospike_api_FcapData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kayzen_impcount_aerospike_api_FcapData_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_com_kayzen_impcount_aerospike_api_FcapData_fcapCampaignOrLineItem_descriptor =
      internal_static_com_kayzen_impcount_aerospike_api_FcapData_descriptor.getNestedTypes().get(0);
    internal_static_com_kayzen_impcount_aerospike_api_FcapData_fcapCampaignOrLineItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kayzen_impcount_aerospike_api_FcapData_fcapCampaignOrLineItem_descriptor,
        new java.lang.String[] { "CampaignOrLineItemID", "Option", "CapType", "CampaignOrLineItem", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
