// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syncbatchupdate.proto

package com.kayzen.impcount.aerospike.api;

public final class Syncbatchupdate {
  private Syncbatchupdate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SyncBatchUpdateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string group = 1 [default = ""];</code>
     * @return Whether the group field is set.
     */
    boolean hasGroup();
    /**
     * <code>optional string group = 1 [default = ""];</code>
     * @return The group.
     */
    java.lang.String getGroup();
    /**
     * <code>optional string group = 1 [default = ""];</code>
     * @return The bytes for group.
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    /**
     * <code>optional string column = 2 [default = ""];</code>
     * @return Whether the column field is set.
     */
    boolean hasColumn();
    /**
     * <code>optional string column = 2 [default = ""];</code>
     * @return The column.
     */
    java.lang.String getColumn();
    /**
     * <code>optional string column = 2 [default = ""];</code>
     * @return The bytes for column.
     */
    com.google.protobuf.ByteString
        getColumnBytes();

    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
     */
    java.util.List<com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row> 
        getRowsList();
    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
     */
    com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row getRows(int index);
    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
     */
    int getRowsCount();
    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
     */
    java.util.List<? extends com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.rowOrBuilder> 
        getRowsOrBuilderList();
    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
     */
    com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.rowOrBuilder getRowsOrBuilder(
        int index);

    /**
     * <code>optional int32 reqcount = 4 [default = 0];</code>
     * @return Whether the reqcount field is set.
     */
    boolean hasReqcount();
    /**
     * <code>optional int32 reqcount = 4 [default = 0];</code>
     * @return The reqcount.
     */
    int getReqcount();
  }
  /**
   * Protobuf type {@code com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest}
   */
  public  static final class SyncBatchUpdateRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest)
      SyncBatchUpdateRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SyncBatchUpdateRequest.newBuilder() to construct.
    private SyncBatchUpdateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SyncBatchUpdateRequest() {
      group_ = "";
      column_ = "";
      rows_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SyncBatchUpdateRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SyncBatchUpdateRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              group_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              column_ = bs;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                rows_ = new java.util.ArrayList<com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row>();
                mutable_bitField0_ |= 0x00000004;
              }
              rows_.add(
                  input.readMessage(com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.PARSER, extensionRegistry));
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              reqcount_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kayzen.impcount.aerospike.api.Syncbatchupdate.internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kayzen.impcount.aerospike.api.Syncbatchupdate.internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.class, com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.Builder.class);
    }

    public interface rowOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string key = 1 [default = ""];</code>
       * @return Whether the key field is set.
       */
      boolean hasKey();
      /**
       * <code>optional string key = 1 [default = ""];</code>
       * @return The key.
       */
      java.lang.String getKey();
      /**
       * <code>optional string key = 1 [default = ""];</code>
       * @return The bytes for key.
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.BinData value = 2;</code>
       * @return Whether the value field is set.
       */
      boolean hasValue();
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.BinData value = 2;</code>
       * @return The value.
       */
      com.kayzen.impcount.aerospike.api.Binvalue.BinData getValue();
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.BinData value = 2;</code>
       */
      com.kayzen.impcount.aerospike.api.Binvalue.BinDataOrBuilder getValueOrBuilder();

      /**
       * <code>optional string option = 3 [default = ""];</code>
       * @return Whether the option field is set.
       */
      boolean hasOption();
      /**
       * <code>optional string option = 3 [default = ""];</code>
       * @return The option.
       */
      java.lang.String getOption();
      /**
       * <code>optional string option = 3 [default = ""];</code>
       * @return The bytes for option.
       */
      com.google.protobuf.ByteString
          getOptionBytes();
    }
    /**
     * Protobuf type {@code com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row}
     */
    public  static final class row extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row)
        rowOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use row.newBuilder() to construct.
      private row(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private row() {
        key_ = "";
        option_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new row();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private row(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                key_ = bs;
                break;
              }
              case 18: {
                com.kayzen.impcount.aerospike.api.Binvalue.BinData.Builder subBuilder = null;
                if (((bitField0_ & 0x00000002) != 0)) {
                  subBuilder = value_.toBuilder();
                }
                value_ = input.readMessage(com.kayzen.impcount.aerospike.api.Binvalue.BinData.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(value_);
                  value_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000002;
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                option_ = bs;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kayzen.impcount.aerospike.api.Syncbatchupdate.internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_row_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kayzen.impcount.aerospike.api.Syncbatchupdate.internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_row_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.class, com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.Builder.class);
      }

      private int bitField0_;
      public static final int KEY_FIELD_NUMBER = 1;
      private volatile java.lang.Object key_;
      /**
       * <code>optional string key = 1 [default = ""];</code>
       * @return Whether the key field is set.
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string key = 1 [default = ""];</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string key = 1 [default = ""];</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private com.kayzen.impcount.aerospike.api.Binvalue.BinData value_;
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.BinData value = 2;</code>
       * @return Whether the value field is set.
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.BinData value = 2;</code>
       * @return The value.
       */
      public com.kayzen.impcount.aerospike.api.Binvalue.BinData getValue() {
        return value_ == null ? com.kayzen.impcount.aerospike.api.Binvalue.BinData.getDefaultInstance() : value_;
      }
      /**
       * <code>optional .com.kayzen.impcount.aerospike.api.BinData value = 2;</code>
       */
      public com.kayzen.impcount.aerospike.api.Binvalue.BinDataOrBuilder getValueOrBuilder() {
        return value_ == null ? com.kayzen.impcount.aerospike.api.Binvalue.BinData.getDefaultInstance() : value_;
      }

      public static final int OPTION_FIELD_NUMBER = 3;
      private volatile java.lang.Object option_;
      /**
       * <code>optional string option = 3 [default = ""];</code>
       * @return Whether the option field is set.
       */
      public boolean hasOption() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string option = 3 [default = ""];</code>
       * @return The option.
       */
      public java.lang.String getOption() {
        java.lang.Object ref = option_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            option_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string option = 3 [default = ""];</code>
       * @return The bytes for option.
       */
      public com.google.protobuf.ByteString
          getOptionBytes() {
        java.lang.Object ref = option_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          option_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeMessage(2, getValue());
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, option_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, getValue());
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, option_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row)) {
          return super.equals(obj);
        }
        com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row other = (com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row) obj;

        if (hasKey() != other.hasKey()) return false;
        if (hasKey()) {
          if (!getKey()
              .equals(other.getKey())) return false;
        }
        if (hasValue() != other.hasValue()) return false;
        if (hasValue()) {
          if (!getValue()
              .equals(other.getValue())) return false;
        }
        if (hasOption() != other.hasOption()) return false;
        if (hasOption()) {
          if (!getOption()
              .equals(other.getOption())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasKey()) {
          hash = (37 * hash) + KEY_FIELD_NUMBER;
          hash = (53 * hash) + getKey().hashCode();
        }
        if (hasValue()) {
          hash = (37 * hash) + VALUE_FIELD_NUMBER;
          hash = (53 * hash) + getValue().hashCode();
        }
        if (hasOption()) {
          hash = (37 * hash) + OPTION_FIELD_NUMBER;
          hash = (53 * hash) + getOption().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row)
          com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.rowOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.kayzen.impcount.aerospike.api.Syncbatchupdate.internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_row_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.kayzen.impcount.aerospike.api.Syncbatchupdate.internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_row_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.class, com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.Builder.class);
        }

        // Construct using com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
            getValueFieldBuilder();
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          if (valueBuilder_ == null) {
            value_ = null;
          } else {
            valueBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          option_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.kayzen.impcount.aerospike.api.Syncbatchupdate.internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_row_descriptor;
        }

        @java.lang.Override
        public com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row getDefaultInstanceForType() {
          return com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.getDefaultInstance();
        }

        @java.lang.Override
        public com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row build() {
          com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row buildPartial() {
          com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row result = new com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) != 0)) {
            if (valueBuilder_ == null) {
              result.value_ = value_;
            } else {
              result.value_ = valueBuilder_.build();
            }
            to_bitField0_ |= 0x00000002;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            to_bitField0_ |= 0x00000004;
          }
          result.option_ = option_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row) {
            return mergeFrom((com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row other) {
          if (other == com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.getDefaultInstance()) return this;
          if (other.hasKey()) {
            bitField0_ |= 0x00000001;
            key_ = other.key_;
            onChanged();
          }
          if (other.hasValue()) {
            mergeValue(other.getValue());
          }
          if (other.hasOption()) {
            bitField0_ |= 0x00000004;
            option_ = other.option_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object key_ = "";
        /**
         * <code>optional string key = 1 [default = ""];</code>
         * @return Whether the key field is set.
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional string key = 1 [default = ""];</code>
         * @return The key.
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              key_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string key = 1 [default = ""];</code>
         * @return The bytes for key.
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string key = 1 [default = ""];</code>
         * @param value The key to set.
         * @return This builder for chaining.
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string key = 1 [default = ""];</code>
         * @return This builder for chaining.
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>optional string key = 1 [default = ""];</code>
         * @param value The bytes for key to set.
         * @return This builder for chaining.
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }

        private com.kayzen.impcount.aerospike.api.Binvalue.BinData value_;
        private com.google.protobuf.SingleFieldBuilderV3<
            com.kayzen.impcount.aerospike.api.Binvalue.BinData, com.kayzen.impcount.aerospike.api.Binvalue.BinData.Builder, com.kayzen.impcount.aerospike.api.Binvalue.BinDataOrBuilder> valueBuilder_;
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.BinData value = 2;</code>
         * @return Whether the value field is set.
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.BinData value = 2;</code>
         * @return The value.
         */
        public com.kayzen.impcount.aerospike.api.Binvalue.BinData getValue() {
          if (valueBuilder_ == null) {
            return value_ == null ? com.kayzen.impcount.aerospike.api.Binvalue.BinData.getDefaultInstance() : value_;
          } else {
            return valueBuilder_.getMessage();
          }
        }
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.BinData value = 2;</code>
         */
        public Builder setValue(com.kayzen.impcount.aerospike.api.Binvalue.BinData value) {
          if (valueBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            value_ = value;
            onChanged();
          } else {
            valueBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.BinData value = 2;</code>
         */
        public Builder setValue(
            com.kayzen.impcount.aerospike.api.Binvalue.BinData.Builder builderForValue) {
          if (valueBuilder_ == null) {
            value_ = builderForValue.build();
            onChanged();
          } else {
            valueBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.BinData value = 2;</code>
         */
        public Builder mergeValue(com.kayzen.impcount.aerospike.api.Binvalue.BinData value) {
          if (valueBuilder_ == null) {
            if (((bitField0_ & 0x00000002) != 0) &&
                value_ != null &&
                value_ != com.kayzen.impcount.aerospike.api.Binvalue.BinData.getDefaultInstance()) {
              value_ =
                com.kayzen.impcount.aerospike.api.Binvalue.BinData.newBuilder(value_).mergeFrom(value).buildPartial();
            } else {
              value_ = value;
            }
            onChanged();
          } else {
            valueBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.BinData value = 2;</code>
         */
        public Builder clearValue() {
          if (valueBuilder_ == null) {
            value_ = null;
            onChanged();
          } else {
            valueBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.BinData value = 2;</code>
         */
        public com.kayzen.impcount.aerospike.api.Binvalue.BinData.Builder getValueBuilder() {
          bitField0_ |= 0x00000002;
          onChanged();
          return getValueFieldBuilder().getBuilder();
        }
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.BinData value = 2;</code>
         */
        public com.kayzen.impcount.aerospike.api.Binvalue.BinDataOrBuilder getValueOrBuilder() {
          if (valueBuilder_ != null) {
            return valueBuilder_.getMessageOrBuilder();
          } else {
            return value_ == null ?
                com.kayzen.impcount.aerospike.api.Binvalue.BinData.getDefaultInstance() : value_;
          }
        }
        /**
         * <code>optional .com.kayzen.impcount.aerospike.api.BinData value = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            com.kayzen.impcount.aerospike.api.Binvalue.BinData, com.kayzen.impcount.aerospike.api.Binvalue.BinData.Builder, com.kayzen.impcount.aerospike.api.Binvalue.BinDataOrBuilder> 
            getValueFieldBuilder() {
          if (valueBuilder_ == null) {
            valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                com.kayzen.impcount.aerospike.api.Binvalue.BinData, com.kayzen.impcount.aerospike.api.Binvalue.BinData.Builder, com.kayzen.impcount.aerospike.api.Binvalue.BinDataOrBuilder>(
                    getValue(),
                    getParentForChildren(),
                    isClean());
            value_ = null;
          }
          return valueBuilder_;
        }

        private java.lang.Object option_ = "";
        /**
         * <code>optional string option = 3 [default = ""];</code>
         * @return Whether the option field is set.
         */
        public boolean hasOption() {
          return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>optional string option = 3 [default = ""];</code>
         * @return The option.
         */
        public java.lang.String getOption() {
          java.lang.Object ref = option_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              option_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string option = 3 [default = ""];</code>
         * @return The bytes for option.
         */
        public com.google.protobuf.ByteString
            getOptionBytes() {
          java.lang.Object ref = option_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            option_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string option = 3 [default = ""];</code>
         * @param value The option to set.
         * @return This builder for chaining.
         */
        public Builder setOption(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          option_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string option = 3 [default = ""];</code>
         * @return This builder for chaining.
         */
        public Builder clearOption() {
          bitField0_ = (bitField0_ & ~0x00000004);
          option_ = getDefaultInstance().getOption();
          onChanged();
          return this;
        }
        /**
         * <code>optional string option = 3 [default = ""];</code>
         * @param value The bytes for option to set.
         * @return This builder for chaining.
         */
        public Builder setOptionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          option_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row)
      }

      // @@protoc_insertion_point(class_scope:com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row)
      private static final com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row();
      }

      public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<row>
          PARSER = new com.google.protobuf.AbstractParser<row>() {
        @java.lang.Override
        public row parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new row(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<row> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<row> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int GROUP_FIELD_NUMBER = 1;
    private volatile java.lang.Object group_;
    /**
     * <code>optional string group = 1 [default = ""];</code>
     * @return Whether the group field is set.
     */
    public boolean hasGroup() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string group = 1 [default = ""];</code>
     * @return The group.
     */
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          group_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string group = 1 [default = ""];</code>
     * @return The bytes for group.
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLUMN_FIELD_NUMBER = 2;
    private volatile java.lang.Object column_;
    /**
     * <code>optional string column = 2 [default = ""];</code>
     * @return Whether the column field is set.
     */
    public boolean hasColumn() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string column = 2 [default = ""];</code>
     * @return The column.
     */
    public java.lang.String getColumn() {
      java.lang.Object ref = column_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          column_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string column = 2 [default = ""];</code>
     * @return The bytes for column.
     */
    public com.google.protobuf.ByteString
        getColumnBytes() {
      java.lang.Object ref = column_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        column_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROWS_FIELD_NUMBER = 3;
    private java.util.List<com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row> rows_;
    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
     */
    public java.util.List<com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row> getRowsList() {
      return rows_;
    }
    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
     */
    public java.util.List<? extends com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.rowOrBuilder> 
        getRowsOrBuilderList() {
      return rows_;
    }
    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
     */
    public int getRowsCount() {
      return rows_.size();
    }
    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
     */
    public com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row getRows(int index) {
      return rows_.get(index);
    }
    /**
     * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
     */
    public com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.rowOrBuilder getRowsOrBuilder(
        int index) {
      return rows_.get(index);
    }

    public static final int REQCOUNT_FIELD_NUMBER = 4;
    private int reqcount_;
    /**
     * <code>optional int32 reqcount = 4 [default = 0];</code>
     * @return Whether the reqcount field is set.
     */
    public boolean hasReqcount() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 reqcount = 4 [default = 0];</code>
     * @return The reqcount.
     */
    public int getReqcount() {
      return reqcount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, group_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, column_);
      }
      for (int i = 0; i < rows_.size(); i++) {
        output.writeMessage(3, rows_.get(i));
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(4, reqcount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, group_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, column_);
      }
      for (int i = 0; i < rows_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, rows_.get(i));
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, reqcount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest)) {
        return super.equals(obj);
      }
      com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest other = (com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest) obj;

      if (hasGroup() != other.hasGroup()) return false;
      if (hasGroup()) {
        if (!getGroup()
            .equals(other.getGroup())) return false;
      }
      if (hasColumn() != other.hasColumn()) return false;
      if (hasColumn()) {
        if (!getColumn()
            .equals(other.getColumn())) return false;
      }
      if (!getRowsList()
          .equals(other.getRowsList())) return false;
      if (hasReqcount() != other.hasReqcount()) return false;
      if (hasReqcount()) {
        if (getReqcount()
            != other.getReqcount()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGroup()) {
        hash = (37 * hash) + GROUP_FIELD_NUMBER;
        hash = (53 * hash) + getGroup().hashCode();
      }
      if (hasColumn()) {
        hash = (37 * hash) + COLUMN_FIELD_NUMBER;
        hash = (53 * hash) + getColumn().hashCode();
      }
      if (getRowsCount() > 0) {
        hash = (37 * hash) + ROWS_FIELD_NUMBER;
        hash = (53 * hash) + getRowsList().hashCode();
      }
      if (hasReqcount()) {
        hash = (37 * hash) + REQCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getReqcount();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest)
        com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kayzen.impcount.aerospike.api.Syncbatchupdate.internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kayzen.impcount.aerospike.api.Syncbatchupdate.internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.class, com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.Builder.class);
      }

      // Construct using com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRowsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        group_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        column_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          rowsBuilder_.clear();
        }
        reqcount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kayzen.impcount.aerospike.api.Syncbatchupdate.internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_descriptor;
      }

      @java.lang.Override
      public com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest getDefaultInstanceForType() {
        return com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest build() {
        com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest buildPartial() {
        com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest result = new com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.group_ = group_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.column_ = column_;
        if (rowsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            rows_ = java.util.Collections.unmodifiableList(rows_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.rows_ = rows_;
        } else {
          result.rows_ = rowsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.reqcount_ = reqcount_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest) {
          return mergeFrom((com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest other) {
        if (other == com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.getDefaultInstance()) return this;
        if (other.hasGroup()) {
          bitField0_ |= 0x00000001;
          group_ = other.group_;
          onChanged();
        }
        if (other.hasColumn()) {
          bitField0_ |= 0x00000002;
          column_ = other.column_;
          onChanged();
        }
        if (rowsBuilder_ == null) {
          if (!other.rows_.isEmpty()) {
            if (rows_.isEmpty()) {
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureRowsIsMutable();
              rows_.addAll(other.rows_);
            }
            onChanged();
          }
        } else {
          if (!other.rows_.isEmpty()) {
            if (rowsBuilder_.isEmpty()) {
              rowsBuilder_.dispose();
              rowsBuilder_ = null;
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000004);
              rowsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRowsFieldBuilder() : null;
            } else {
              rowsBuilder_.addAllMessages(other.rows_);
            }
          }
        }
        if (other.hasReqcount()) {
          setReqcount(other.getReqcount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object group_ = "";
      /**
       * <code>optional string group = 1 [default = ""];</code>
       * @return Whether the group field is set.
       */
      public boolean hasGroup() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string group = 1 [default = ""];</code>
       * @return The group.
       */
      public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            group_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string group = 1 [default = ""];</code>
       * @return The bytes for group.
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string group = 1 [default = ""];</code>
       * @param value The group to set.
       * @return This builder for chaining.
       */
      public Builder setGroup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string group = 1 [default = ""];</code>
       * @return This builder for chaining.
       */
      public Builder clearGroup() {
        bitField0_ = (bitField0_ & ~0x00000001);
        group_ = getDefaultInstance().getGroup();
        onChanged();
        return this;
      }
      /**
       * <code>optional string group = 1 [default = ""];</code>
       * @param value The bytes for group to set.
       * @return This builder for chaining.
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        group_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object column_ = "";
      /**
       * <code>optional string column = 2 [default = ""];</code>
       * @return Whether the column field is set.
       */
      public boolean hasColumn() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string column = 2 [default = ""];</code>
       * @return The column.
       */
      public java.lang.String getColumn() {
        java.lang.Object ref = column_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            column_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string column = 2 [default = ""];</code>
       * @return The bytes for column.
       */
      public com.google.protobuf.ByteString
          getColumnBytes() {
        java.lang.Object ref = column_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          column_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string column = 2 [default = ""];</code>
       * @param value The column to set.
       * @return This builder for chaining.
       */
      public Builder setColumn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        column_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string column = 2 [default = ""];</code>
       * @return This builder for chaining.
       */
      public Builder clearColumn() {
        bitField0_ = (bitField0_ & ~0x00000002);
        column_ = getDefaultInstance().getColumn();
        onChanged();
        return this;
      }
      /**
       * <code>optional string column = 2 [default = ""];</code>
       * @param value The bytes for column to set.
       * @return This builder for chaining.
       */
      public Builder setColumnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        column_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row> rows_ =
        java.util.Collections.emptyList();
      private void ensureRowsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          rows_ = new java.util.ArrayList<com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row>(rows_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row, com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.Builder, com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.rowOrBuilder> rowsBuilder_;

      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
       */
      public java.util.List<com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row> getRowsList() {
        if (rowsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rows_);
        } else {
          return rowsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
       */
      public int getRowsCount() {
        if (rowsBuilder_ == null) {
          return rows_.size();
        } else {
          return rowsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
       */
      public com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row getRows(int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);
        } else {
          return rowsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
       */
      public Builder setRows(
          int index, com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.set(index, value);
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
       */
      public Builder setRows(
          int index, com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.set(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
       */
      public Builder addRows(com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
       */
      public Builder addRows(
          int index, com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(index, value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
       */
      public Builder addRows(
          com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
       */
      public Builder addRows(
          int index, com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
       */
      public Builder addAllRows(
          java.lang.Iterable<? extends com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row> values) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rows_);
          onChanged();
        } else {
          rowsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
       */
      public Builder clearRows() {
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
       */
      public Builder removeRows(int index) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.remove(index);
          onChanged();
        } else {
          rowsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
       */
      public com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.Builder getRowsBuilder(
          int index) {
        return getRowsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
       */
      public com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.rowOrBuilder getRowsOrBuilder(
          int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);  } else {
          return rowsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
       */
      public java.util.List<? extends com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.rowOrBuilder> 
           getRowsOrBuilderList() {
        if (rowsBuilder_ != null) {
          return rowsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rows_);
        }
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
       */
      public com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.Builder addRowsBuilder() {
        return getRowsFieldBuilder().addBuilder(
            com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.getDefaultInstance());
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
       */
      public com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.Builder addRowsBuilder(
          int index) {
        return getRowsFieldBuilder().addBuilder(
            index, com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.getDefaultInstance());
      }
      /**
       * <code>repeated .com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest.row rows = 3;</code>
       */
      public java.util.List<com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.Builder> 
           getRowsBuilderList() {
        return getRowsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row, com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.Builder, com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.rowOrBuilder> 
          getRowsFieldBuilder() {
        if (rowsBuilder_ == null) {
          rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row, com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.row.Builder, com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest.rowOrBuilder>(
                  rows_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          rows_ = null;
        }
        return rowsBuilder_;
      }

      private int reqcount_ ;
      /**
       * <code>optional int32 reqcount = 4 [default = 0];</code>
       * @return Whether the reqcount field is set.
       */
      public boolean hasReqcount() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 reqcount = 4 [default = 0];</code>
       * @return The reqcount.
       */
      public int getReqcount() {
        return reqcount_;
      }
      /**
       * <code>optional int32 reqcount = 4 [default = 0];</code>
       * @param value The reqcount to set.
       * @return This builder for chaining.
       */
      public Builder setReqcount(int value) {
        bitField0_ |= 0x00000008;
        reqcount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 reqcount = 4 [default = 0];</code>
       * @return This builder for chaining.
       */
      public Builder clearReqcount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        reqcount_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest)
    }

    // @@protoc_insertion_point(class_scope:com.kayzen.impcount.aerospike.api.SyncBatchUpdateRequest)
    private static final com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest();
    }

    public static com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SyncBatchUpdateRequest>
        PARSER = new com.google.protobuf.AbstractParser<SyncBatchUpdateRequest>() {
      @java.lang.Override
      public SyncBatchUpdateRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SyncBatchUpdateRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SyncBatchUpdateRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SyncBatchUpdateRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kayzen.impcount.aerospike.api.Syncbatchupdate.SyncBatchUpdateRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_row_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_row_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025syncbatchupdate.proto\022!com.kayzen.impc" +
      "ount.aerospike.api\032\016binvalue.proto\"\200\002\n\026S" +
      "yncBatchUpdateRequest\022\017\n\005group\030\001 \001(\t:\000\022\020" +
      "\n\006column\030\002 \001(\t:\000\022K\n\004rows\030\003 \003(\0132=.com.kay" +
      "zen.impcount.aerospike.api.SyncBatchUpda" +
      "teRequest.row\022\023\n\010reqcount\030\004 \001(\005:\0010\032a\n\003ro" +
      "w\022\r\n\003key\030\001 \001(\t:\000\0229\n\005value\030\002 \001(\0132*.com.ka" +
      "yzen.impcount.aerospike.api.BinData\022\020\n\006o" +
      "ption\030\003 \001(\t:\000"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kayzen.impcount.aerospike.api.Binvalue.getDescriptor(),
        });
    internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_descriptor,
        new java.lang.String[] { "Group", "Column", "Rows", "Reqcount", });
    internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_row_descriptor =
      internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_row_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kayzen_impcount_aerospike_api_SyncBatchUpdateRequest_row_descriptor,
        new java.lang.String[] { "Key", "Value", "Option", });
    com.kayzen.impcount.aerospike.api.Binvalue.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
