source ./tables/impression_tables.sql
source ./tables/aerospike_tables.sql
source ./procedures/utility_procedures.sql
source ./procedures/dynamic_expiry_procedures.sql
source ./procedures/impression_count_procedures.sql
source ./procedures/aerospike_procedures.sql
source ./procedures/dynamic_partition_procedures.sql
source ./triggers/impression_count_triggers.sql
source ./events/impression_count_event.sql